### ISSUE TITLE
qml: display caret pos in status bar

### ISSUE THREAD

**Issue by gwenzek** [limetext/lime-qml#15] opened 2015-11-05 19:55 UTC
As stated on #14 I'd like to display the caret position inside the status bar.

I tried to add a [signal](https://github.com/gwenzek/lime-qml/blob/116a71d1e1b2d366b5e45f3578ee3f8eea143fec/main/LimeView.qml#L27) going from the `LimeView` `Mouse Area` to the main view.
The signal is [fired](https://github.com/gwenzek/lime-qml/blob/116a71d1e1b2d366b5e45f3578ee3f8eea143fec/main/LimeView.qml#L186) on mouse pressed, but it's [not caught](https://github.com/gwenzek/lime-qml/blob/116a71d1e1b2d366b5e45f3578ee3f8eea143fec/main/main.qml#L270) by the main view.

I tried another way to register the signal handler, with a [`Component.onCompleted`](https://github.com/gwenzek/lime-qml/blob/116a71d1e1b2d366b5e45f3578ee3f8eea143fec/main/main.qml#L272) but it doesn't seem to be called either.

It's my first experience with qml, so I may be missing something simple. I read various documentation on signals, and created a toy application with a similar structure without problem. So I don't know where to look next. Any help would be welcome.

**Comment by erbridge** [comment] 2015-11-06 11:26
I'm not very familiar with QML, either, but I don't see anything obviously wrong. Maybe @zoli might have some ideas?

**Comment by zoli** [comment] 2016-04-13 19:33
I think we should listen to `OnSelectionModified` event in frontendView and from there set status bar

**Comment by zoli** [comment] 2016-05-22 16:45
This is duplicate of #3.

**Closed as completed by zoli** 2016-05-22 16:45 UTC
