### ISSUE TITLE
build success with only 1 warning, but cannot run

### ISSUE THREAD

**Issue by learning** [limetext/lime-qml#48] opened 2017-07-06 08:13 UTC
- macOS 10.12.5
- Go 1.5.4
- qt5 5.9.1

build success, only 1 warning

```shell
~/.gopath/src/github.com/limetext/lime-qml/main
% go build
# github.com/limetext/qml-go
In file included from ../../qml-go/all.cpp:6:
In file included from ../../qml-go/cpp/goitemmodel_api.cpp:4:
In file included from ./cpp/util.cpp:2:
./cpp/util.h:13:9: warning: 'QStringFromGoString' has C-linkage specified, but returns user-defined type 'QString' which is incompatible with C [-Wreturn-type-c-linkage]
```

but it can't run properly
```shell
./main
[1]    71984 killed     ./main
```

**Comment by zoli** [comment] 2017-12-19 12:46
duplicate of https://github.com/limetext/qml-go/issues/9.

**Closed as completed by zoli** 2017-12-19 12:46 UTC
